# Generated by Django 4.0.6 on 2022-10-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='F.I.SH')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='Telefon raqam')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username*')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('last_login_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('superuser', models.BooleanField(default=False, verbose_name='SuperAdmin')),
                ('staff', models.BooleanField(default=False, verbose_name='xodim')),
                ('data_add', models.BooleanField(default=False, verbose_name="Malumot to'ldiruvchi")),
                ('data_viewer', models.BooleanField(default=False, verbose_name='Malumotlarni kuzatuvchi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
