# Generated by Django 4.0.6 on 2022-09-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='data_add',
            field=models.BooleanField(default=False, verbose_name="Malumot to'ldiruvchi"),
        ),
    ]
