# Generated by Django 4.0.6 on 2022-09-05 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bitiruvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=300, verbose_name='F.I.Sh')),
                ('img', models.ImageField(default='default/default.png', upload_to='bitiruvchilar-foto/', verbose_name='Rasm')),
                ('t_sana', models.DateField(blank=True, null=True, verbose_name="Tug'ulgan sana")),
                ('jins', models.CharField(choices=[("o'g'il bola", "o'g'il bola"), ('qiz bola', 'qiz bola')], default="o'g'il bola", max_length=300, verbose_name='Jinsi')),
                ('uy', models.CharField(blank=True, max_length=300, null=True, verbose_name="Ko'cha nomi 45uy")),
                ('phone', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefon raqam (+998) ')),
                ('email', models.EmailField(blank=True, max_length=300, null=True, verbose_name='E-Pochta')),
                ('idea', models.CharField(choices=[('Bor', 'Bor'), ('Yoq', 'Yoq')], default='Yoq', max_length=300, verbose_name="Biznes g'oya")),
                ('short_f', models.CharField(blank=True, max_length=10000, null=True, verbose_name="Bizness g'oya haqqida qisqacha (agar bor bo'lsa)")),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChetTili',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='Imkonyat',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='Kollej',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='Maktab',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
                ('status', models.CharField(blank=True, choices=[("O'rta ta'lim maktabi", "O'rta ta'lim maktabi"), ('Ixtisoslashgan maktablar', 'Ixtisoslashgan maktablar')], default="O'rta ta'lim maktabi", max_length=300, null=True)),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='Qiziqish',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='TumanVaShahar',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
                ('status', models.CharField(choices=[('tuman', 'tuman'), ('shahar', 'shahar')], default='shaxar', max_length=300)),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='TypeKollej',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='Universitet',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='Vil',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='UniversitetBitiruvchisi',
            fields=[
                ('bitiruvchi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.bitiruvchi')),
                ('stu_way', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mutaxasislik')),
                ('other_un', models.CharField(blank=True, max_length=300, null=True, verbose_name='ChetEl OTM')),
                ('stu_way_ch', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mutaxasislik')),
                ('maqsad', models.CharField(choices=[("O'qishni davom etirmoqchi", "O'qishni davom etirmoqchi"), ('Ishlamoqchi', 'Ishlamoqchi')], default='Ishlamoqchi', max_length=300, verbose_name='Maqsadi')),
                ('universiteT', models.CharField(blank=True, max_length=300, null=True, verbose_name='Bitirayotgan OTM')),
                ('guvohnoma', models.ManyToManyField(related_name='guvohnomaU', to='main.driverlicense', verbose_name='Haydovchilik Guvohnomasi')),
                ('universitet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.universitet', verbose_name='Bitirayotgan OTM')),
                ('vil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vil')),
            ],
            bases=('main.bitiruvchi',),
        ),
        migrations.AddField(
            model_name='universitet',
            name='viloyat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vil', verbose_name='viloyat nomi'),
        ),
        migrations.CreateModel(
            name='MaktabBitiruvchisi',
            fields=[
                ('bitiruvchi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.bitiruvchi')),
                ('sinf', models.CharField(choices=[('9-sinf', '9-sinf'), ('11-sinf', '11-sinf')], default='9-sinf', max_length=300, verbose_name='Sinf')),
                ('stu_way_un', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mutaxasislik')),
                ('other_un', models.CharField(blank=True, max_length=300, null=True, verbose_name='ChetEl OTM nomi')),
                ('stu_way_ch', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mutaxasislik')),
                ('univer_sity', models.CharField(blank=True, max_length=300, null=True, verbose_name="Topshirmoqchi bo'lgan universitet")),
                ('maktab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maktab', verbose_name='Bitirayotgan maktab')),
                ('otm_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.universitet', verbose_name="Topshirmoqchi bo'lgan OTM Nomi")),
                ('tuman_mk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tumanvashahar', verbose_name='Maktab manzili')),
                ('vil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mk_vil', to='main.vil', verbose_name='OTM manzili')),
            ],
            bases=('main.bitiruvchi',),
        ),
        migrations.AddField(
            model_name='maktab',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tumanvashahar', verbose_name='Qaysi tuman'),
        ),
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('autotime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autotime')),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tumanvashahar', verbose_name='Qaysi tuman')),
            ],
            bases=('main.autotime',),
        ),
        migrations.CreateModel(
            name='KollejBitiruvchisi',
            fields=[
                ('bitiruvchi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.bitiruvchi')),
                ('stu_way', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mutaxasislik')),
                ('maqsad', models.CharField(choices=[("O'qishni davom etirmoqchi", "O'qishni davom etirmoqchi"), ('Ishlamoqchi', 'Ishlamoqchi')], default='Ishlamoqchi', max_length=300, verbose_name='Maqsadi')),
                ('stu_way_un', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mutaxasislik')),
                ('other_un', models.CharField(blank=True, max_length=300, null=True, verbose_name='chetel otm')),
                ('stu_way_ch', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mutaxasislik')),
                ('kolleJ', models.CharField(blank=True, max_length=300, null=True, verbose_name='Bitirayotgan kollej')),
                ('univer_sity', models.CharField(blank=True, max_length=300, null=True, verbose_name="Topshirmoqchi bo'lgan universitet")),
                ('guvohnoma', models.ManyToManyField(related_name='guvohnomaK', to='main.driverlicense', verbose_name='Haydovchilik Guvohnomasi')),
                ('kollej', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kollej', verbose_name='Bitirayotgan Kollej')),
                ('otm_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.universitet')),
                ('tuman_kj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tumanvashahar', verbose_name='Kollej manzili')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.typekollej', verbose_name="Professional ta'lim")),
                ('vil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kj_vil', to='main.vil')),
            ],
            bases=('main.bitiruvchi',),
        ),
        migrations.AddField(
            model_name='kollej',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tumanvashahar', verbose_name='Qaysi tuman'),
        ),
        migrations.AddField(
            model_name='kollej',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.typekollej', verbose_name="Ta'lim muassasasi turi"),
        ),
        migrations.AddField(
            model_name='bitiruvchi',
            name='chettili',
            field=models.ManyToManyField(related_name='f_lang', to='main.chettili'),
        ),
        migrations.AddField(
            model_name='bitiruvchi',
            name='imkonyat',
            field=models.ManyToManyField(related_name='abilty', to='main.imkonyat', verbose_name='Kompyuter bilimi'),
        ),
        migrations.AddField(
            model_name='bitiruvchi',
            name='mahalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mahalla', verbose_name='Mahalla Nomi'),
        ),
        migrations.AddField(
            model_name='bitiruvchi',
            name='qiziqish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='main.qiziqish', verbose_name='Qiziqish'),
        ),
        migrations.AddField(
            model_name='bitiruvchi',
            name='sport',
            field=models.ManyToManyField(related_name='sport', to='main.sport', verbose_name='Qiziqadigan sport turi'),
        ),
        migrations.AddField(
            model_name='bitiruvchi',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tumanvashahar', verbose_name='Yashaydigan tuman(shahar)'),
        ),
    ]
