# Generated by Django 4.0.6 on 2022-09-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kollejbitiruvchisi',
            name='kolleJ',
        ),
        migrations.RemoveField(
            model_name='kollejbitiruvchisi',
            name='univer_sity',
        ),
        migrations.RemoveField(
            model_name='maktabbitiruvchisi',
            name='univer_sity',
        ),
        migrations.RemoveField(
            model_name='universitetbitiruvchisi',
            name='universiteT',
        ),
    ]
